typography_spectrum: 0.8420174466446042
color:
  brandStrength: 0.704565181164071
  lightness: 0.43630575900897384
  saturation: 0.584681469714269
  rhythmicContrast: 0.7385369199328125
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.927941353758797
author:
  name: COLECTIVO 35
name: COLECTIVO 35
